[package]
name = "tera-template"
version = "0.1.0"
authors = ["David Wood <david@davidtw.co>"]
edition = "2018"

[[bin]]
name = "tera-template"
path = "main.rs"

[dependencies]
anyhow = "1.0.31"
serde_json = "1.0.53"
structopt = "0.3.14"
tera = "1.3.0"
